#!/bin/sh
. "$(dirname -- "$0")/_/husky.sh"

if [[ "$OSTYPE" == "msys" ]] || [[ "$OSTYPE" == "cygwin" ]] || [[ "$OSTYPE" == "win32" ]]; then
  npx.cmd --no -- commitlint --edit $1
else
  npx --no -- commitlint --edit $1
fi